export const basePermissions = [
  'park_select', 'car_list', 'settings_list_create'
]
// export const usersManagement = [
// 'user_list_create',
// 'user_update_destroy',
// 'log_list',
// 'role_list_create',
// 'role_update_destroy'
// ]
export const parksManagement = [
  'park_list_create',
  'park_delete',
  'park_select',
  'report',
  'open_driver_info'
]
export const driversManagement = [
  'driver_list_create',
  'driver_get_update_delete',
  'driver_ratings',
  'driver_rating_create',
  'drivers_save'
  // 'statistics_personal_drivers_result'
]
export const carsManagement = [
  'car_list',
  'car_condition_list_create',
  'car_condition_update',
  'cars_save',
  'car_id'
]
export const scheduleManagement = [
  'schedule_list_create',
  'schedule_get_update_delete',
  'schedule_drivers',
  'statistics_schedule_report_exel',
  'contracts',
  'investors-list',
  'investors-detail',
  'cars_without_investors',
  'contract_create',
  'region_parks',
  'region_park',
  'region_park_drivers_unbind',
  'region_park_drivers_bind',
  'statistic_schedule',
  'schedule_transplant_driver'
]
export const maintenanceManagement = [
  'ware_houses',
  'spare_parts',
  'spare_part',
  'decommission_parts',
  'decommission_part',
  'spare_part_categories',
  'spare_part_category',
  'order',
  'unit_measure',
  'supplierspark_list_create',
  'supplier',
  'suppliers',
  'orders',
  'maintenance_types',
  'maintenance_work',
  'maintenance_work_id',
  'maintenance_work_history_id',
  'maintenance_work_history',
  'accept_maintenance',
  'return_car_online',
  'ware_house',
  'movement_history',
  'scrapped_history',
  'scrapped_history_spare_part',
  'movement_history_spare_part'
]
export const statisticsManagement = [
  'statistics_car_load',
  'statistics_general_finance',
  'statistics_drivers_income',
  'statistics_drivers_debts',
  'statistics_fines',
  'statistics_personal_drivers_result',
  'statistics_cars_result',
  'driver_open_transactions'
]
export const financialManagement = [
  'statistics_personal_drivers_income',
  'statistics_personal_drivers_income_history',
  'statistics_detail_personal_driver_income',
  'statistics_personal_driver_approve_calculation',
  'statistics_transaction_create',
  'statistics_transaction_defray',
  'schedules_get_not_calculated',
  'statistics_drivers_income_excel',
  'statistics_transaction_delete',
  'drivers_in_change',
  'tenants_income_history',
  'approve_calculation',
  'personal_driver_income',
  'park_monthly_reportregion_parks',
  'transactions',
  'park_monthly_report',
  'fines',
  'fine_by_id',
  'fine_driver_binding',
  'fine_approve',
  'fine_approve_find',
  'fine_change_company_payment',
  'transfer_transactions',
  'transactions_from_driver',
  'dashboard_finance',
  'dashboard_car_load',
  'dashboard_tenants_income',
  'dashboard_fines',
  'dashboard_debts',
  'dashboard_maintenance',
  'dashboard_maintenance_expense',
  'call_update_schedule_five_minutely',
  'retentions_min_max_sum',
  'configurator_check_formula',
  'tenants_income_formula',
  'change_driver_balance',
  'driver_balance_history'
]
export const permissions = {
  // superuser_create: 'Создать суперюзера',
  // user_list_create: 'Создание и просмотр пользователей',
  // user_update_destroy: 'Изменение и удаление пользователей',
  // log_list: 'Просматривать лог действий пользователй',
  // urlnames_list: 'Получить список доступов',
  // role_list_create: 'Создание и просмотр ролей',
  // role_update_destroy: 'Изменение и удаление ролей',
  park_list_create: 'Создание и просмотр парков',
  park_delete: 'Удаление парков',
  park_select: 'Изменять выбранный парк',
  driver_list_create: 'Создание и просмотр арендаторов',
  driver_get_update_delete: 'Изменение и удаление арендаторов',
  driver_ratings: 'Просмотр рейтинга арендаторов',
  driver_rating_create: 'Добавлять запить в рейтинг арендатора',
  // drivers_save: 'Скопировать водителей из яндекса',
  car_list: 'Список автомобилей',
  car_condition_list_create: 'Создание и просмотр состояний автомобилей',
  car_condition_update: 'Изменение состояний автомобилей',
  schedule_list_create: 'Создание и просмотр записей в расписании',
  schedule_get_update_delete: 'Изменение и удаление записей в расписании',
  schedule_drivers: 'Получение списка подходящих к расписанию арендаторов',
  maintenance_list_create: 'Создание и просмотр записей о техобслуживании',
  maintenance_get_update: 'Изменение записей о техобслуживании',
  maintenance_done: 'Подтверждение окончания техобслуживания',
  statistics_car_load: 'Просмотр статистики о загруженности автомобилей',
  statistics_general_finance: 'Просмотр основной финансовой статистики',
  statistics_drivers_income: 'Просмотр статистики о доходах арендаторов',
  statistics_drivers_debts: 'Просмотр статистики по долгам водителей по ремонту автомобилей по вине водителя',
  statistics_fines: 'Просмотр статистики по штрафам',
  statistics_personal_drivers_income: 'Просмотр дохода арендаторов',
  statistics_personal_drivers_income_history: 'Просмотр истории доходов арендаторов',
  statistics_detail_personal_driver_income: 'Просмотр подробостей дохода арендатора',
  statistics_personal_driver_approve_calculation: 'Расчет арендатора',
  statistics_personal_drivers_result: 'Просмотр сводного по арендаторам',
  statistics_cars_result: 'Просмотр сводного по автомобилям',
  statistics_transaction_create: 'Создание взыскания арендатора',
  statistics_transaction_defray: 'Закрывать взыскания мимо кассы',
  supplier_list_create: 'Создание и просмотр поставщиков',
  supplier_get_update_delete: 'Изменение и удаление поставщиков',
  part_list_create: 'Создание и просмотр запчастей',
  part_update: 'Изменение запчастей',
  order_list_create: 'Создание и просмотр заказов на запчасти',
  order_update: 'Изменение заказов на запчасти',
  settings_list_create: 'Изменение и просмотр настроек CRM',
  schedules_get_not_calculated: 'Просмотр календаря по доходам арендаторов',
  statistics_drivers_income_excel: 'Получение отчета по доходам арендаторов в Exel',
  statistics_schedule_report_exel: 'Получение отчета по календарю в Exel',
  drivers_save: 'Обновление списка водителей',
  cars_save: 'Обновление списка машин',
  contracts: 'Получение договоров',
  'investors-list': 'Просмотр Собственников',
  'investors-detail': 'Просмотр,редактирование,удаление ивестора',
  cars_without_investors: 'Получение машин для Собственников',
  car_id: 'Получение данных о машине',
  contract_create: 'Создание договоров',
  report: 'Получение отчета по парку',
  statistics_transaction_delete: 'Удаление транзакции',
  drivers_in_change: 'Список водителей для доплат',
  ware_houses: 'Список склада',
  spare_parts: 'Список запчастей',
  spare_part: 'Запчасть',
  decommission_parts: 'Списанные запчасти',
  decommission_part: 'Списанная запчасть',
  spare_part_categories: 'Категории запчастей',
  spare_part_category: 'Категория запчасти',
  order: 'Заказ',
  unit_measure: 'Единицы измерений',
  supplierspark_list_create: 'Создание поставщиков',
  supplier: 'Поставщик',
  suppliers: 'Поставщики',
  orders: 'Заказы',
  maintenance_types: 'Типы ремонтов',
  maintenance_work: 'ТО',
  maintenance_work_id: 'Конкретное ТО',
  maintenance_work_history_id: 'История ТО машины',
  maintenance_work_history: 'История ТО',
  accept_maintenance: 'Подтвердить завершение ТО',
  driver_open_transactions: 'Получение долгов водителей',
  region_parks: 'Получить районные парки',
  region_park: 'Обновить районный парк',
  region_park_drivers_unbind: 'Открепить водителя от парка',
  region_park_drivers_bind: 'Вернуть открепленного водителя в парк',
  statistic_schedule: 'Статистика расписания',
  return_car_online: 'Вернуть авто на линию',
  car_short_info: 'Список автомобилей(short_info)',
  driver_short_info: 'Список водителей(short_info)',
  open_driver_info: 'Статистика водителя(для бота)',
  driver_open_transaction_info: 'Долги водителя',
  drivers_open_transactions: 'Реест должников',
  history_settings_changes: 'История изменений процента водителя в доходе арендатора',
  change_driver_percent: 'Именение процента водителя в доходе арендатора',
  tenants_income_history: 'Получить доход арендатора (новое)',
  approve_calculation: 'Утвердить рассчет водителя (новое)',
  park_monthly_reportregion_parks: 'Ежемесячный отчет',
  transactions: 'Создание транзакции',
  ware_house: 'Склад (редактирование)',
  movement_history: 'Движение склада',
  scrapped_history: 'История списаний',
  scrapped_history_spare_part: 'История списаний по запчасти',
  movement_history_spare_part: 'Истоия движения по запчасти',
  park_monthly_report: 'Ежемесячный отчет',
  fines: 'Штрафы. Список штрафов',
  fine_by_id: 'Штрафы. Получить информацию по штрафу',
  fine_driver_binding: 'Штрафы. Назначить водителя',
  fine_approve: 'Штрафы. Подтвердить штрав к не удержанным',
  fine_approve_find: 'Штрафы. Подтвердить штрав к найденным',
  fine_change_company_payment: 'Штрафы. Изменить состояние оплаты компанией',
  transfer_transactions: 'Доход арендатора. Перенос транзакций на следующую смену',
  next_driver_schedule_change: 'Для бота. Получить следующую смену водителя',
  get_car_maintenance_info: 'Для бота. Получить информацию по ТО',
  open_driver_info_v: 'Для бота. Общая информация по водителям',
  open_driver_contracts: 'Для бота. Информация по договорам водителя закрепленного за машиной',
  open_sign_driver_contracts: 'Для бота. Подписание договоров',
  transactions_from_driver: 'Доход арендатора. Создание удержания с карточки водителя',
  schedule_transplant_driver: 'Расписание.Пересадить водителя на другое авто',
  dashboard_finance: 'Дэшборд. Финансы',
  dashboard_car_load: 'Дэшборд. Загрузка парка',
  dashboard_tenants_income: 'Дэшборд. Доход арендаторов',
  dashboard_fines: 'Дэшборд. Долги арендаторов',
  dashboard_debts: 'Дэшборд. Штрафы',
  dashboard_maintenance: 'Дэшборд. Сервис',
  dashboard_maintenance_expense: 'Дэшборд. Расходы на сервис',
  open_driver_work_car: 'Бот. Получить рабочее авто водителя',
  call_update_schedule_five_minutely: 'Выплаты и Расписание. Обновить информацию по смене',
  retentions_min_max_sum: 'Выплаты и Расписание. Получить максимальную и минимальную сумму удержаний',
  configurator_check_formula: 'Выплаты,Расписание, Конфигуратор. Проверка формулы',
  tenants_income_formula: 'Конфигуратор. Получение формул и редактирование',
  change_driver_balance: 'Выплаты. Изменение баланса водителя',
  driver_balance_history: 'Выплаты. Получение истории баланса водителя'
}
